spring:
  application:
    name: config-server
  cloud:
    config:
      label:  master
      server:
        git:
          uri:  https://github.com/18292183200/springboot
          searchPaths:  springboot-server-config/cloud-config-repo/
          username: 18292183200@139.com
          password: ..didi1314         
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone:  http://127.0.0.1:9999/eureka/
