spring:
  application:
    name: config-client
  cloud:
    config:
      label:  master
      profile:  test
      discovery:
        enabled:  true
        serviceId:  config-server
        
server:
  port: 8882

eureka:
  client:
    serviceUrl:
      defaultZone:  http://127.0.0.1:9999/eureka/